[general]
working_directory = "/home/ercntreras"
live_config_reload = true

[window]
padding = { x = 0, y = 0 }
opacity = 0.95
#blur = true
title = "Alacritty"

[env]
#TERM = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 250
blink_timeout = 0

[font]
size = 8

[terminal]
#shell = { program = "/bin/bash", args = ["-l"] }
